
•	Algorithmus entwerfen um das Mesh in eine Adjazenzmatrix zu übersetzen. Evtll auch schon testweise implementieren. Fürs erste reichts wenn nur mal 1er in der Matrix stehen.

•	Mach dir bitte auch Gedanken, welche Parameter wir für die Initialisierung brauchen

Hab vergessen das ncoh in die Mal zu geben: Bezüglich Mesh schau dir auch bitte Punk 6 - Variations an, ob wir das mit unserer Struktur implementieren könnenn. Meiner Meinung sollten wir den bias einfach auf die einzelnen Matrixelemente draufmultiplizieren können, aber ich bin mir da nicht 100% sicher

In [2]:
import math
import numpy

In [3]:
nnodes = 9
n = int(nnodes**0.5)

nodes = []
for i in range(nnodes): nodes.append(i)
nodes = numpy.array(nodes)
nodes.shape = (n,n)
nodes       

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# neighbours = numpy.zeros([nnodes, nnodes])
A = numpy.zeros([nnodes,nnodes])
for x in range(n):
    for y in range(n):
        
        neighbours = []
        if(x>0 and x<n-1): #center nodes
            neighbours.append(nodes[y-1,x])
            print(x,y)
        #for k in neighbours:
            A[x,y] = 11
print(A)


1 0
1 1
1 2
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [11. 11. 11.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [ ]:
#position of finite element in 9x9 mes
def posFE(FE):
    posFEx = math.ceil(((FE-2)%18)/2)
    posFEy = math.ceil((FE-2)/18-1)
    posrel = "lower"
    if FE%2 == 0: posrel = "upper"
    return [posFEx, posFEy, posrel]


#returns adjacency matrix for regular mesh in Figure 1 (assignment)
def generate_adjacency(nnodes):

    if int(nnodes**0.5)*int(nnodes**0.5)!=nnodes: return "[ENTER NODE NUMBER OF SQUARE-SHAPED DOMAIN]"

    n = int(nnodes**0.5)
    A = numpy.zeros([nnodes,nnodes])

    #fill matrix neglecting boundary nodes
    hshift = 1 #horizontal shift
    vshift = n #vertical shift
    dshift = n - 1 #diagonal shift from bottom right to upper left
    dshift2 = n + 1 #diagonal shift other direction (not used!)
    for i in range(nnodes-hshift): #horizontal
        A[i,i+hshift] = 1
        A[i+hshift,i] = 1
    for i in range(nnodes-vshift): #vertical
        A[i,i+vshift] = 1
        A[i+vshift,i] = 1
    for i in range(nnodes-dshift): #diagonal
        A[i,i+dshift] = 1
        A[i+dshift,i] = 1
    
    #correct boundary nodes
    hskip = n
    dskip = n
    for i in range(n,nnodes-hshift,hskip): #horizontal
        A[i-hshift,i] = 0
        A[i,i-hshift] = 0
    #vertikal muss nicht korrigert werden
    for i in range(n-1,nnodes,dskip): #diagonal
        A[i-dshift,i] = 0
        A[i,i-dshift] = 0

    return A

In [ ]:
print(posFE(FE=40))
print(generate_adjacency(nnodes=16))